# Generated by Django 4.2.7 on 2023-11-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='nome',
            new_name='marca',
        ),
        migrations.AddField(
            model_name='carro',
            name='modelo',
            field=models.CharField(default='Sem Modelo', max_length=100),
        ),
    ]
