# Generated by Django 4.2.7 on 2023-11-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nome_carro_marca_carro_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='anoFabricacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
