# Generated by Django 4.2.7 on 2023-11-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carro_anofabricacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='potenciaCV',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
