# Generated by Django 4.2.7 on 2023-11-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_carro_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='imgUrl',
            field=models.CharField(max_length=500),
        ),
    ]
